@page "/tramites/entregados/revisar/{TramiteId:int}"

@inject IPeticionesHttp Http
@inject IMostrarMensaje Mensaje
@inject NavigationManager Navigation
@inject IGeneraRegistroActividad Registro

@attribute [Authorize]

<div class="p-4">
    <h1 class="mb-4">Revisi&oacute;n de tr&aacute;mite para entregar</h1>

    <AuthorizeView>
        <BSButtonGroup Class="mb-4">
            @if (context.User.IsInRole("Administrador"))
            {
                <BSButton OnClick="Finalizar" Color="BSColor.Primary" IsOutlined="true">Finalizar tr&aacute;mite</BSButton>
                <a href="/tramites/editar/@TramiteId" class="btn btn-outline-primary">Editar</a>
                <BSButton OnClick="Archivar" Color="BSColor.Danger" IsOutlined="true">Archivar tr&aacute;mite</BSButton>
            }
            else if (context.User.IsInRole("Receptor"))
            {
                <a href="/tramites/editar/@TramiteId" class="btn btn-outline-primary">Editar</a>
            }
            else if (context.User.IsInRole("Técnico"))
            {
                <BSButton OnClick="Finalizar" Color="BSColor.Primary" IsOutlined="true">Finalizar tr&aacute;mite</BSButton>
                <a href="/tramites/editar/@TramiteId" class="btn btn-outline-primary">Editar</a>
            }
        </BSButtonGroup>
    </AuthorizeView>

    <VerTramite Tramite="Tramite" @key="Tramite.TramiteId" />
</div>

@code
{
    [Parameter]
    public int? TramiteId { get; set; }

    [CascadingParameter]
    public Task<AuthenticationState>? Authentication { get; set; }

    private TramiteDTO Tramite { get; set; } = new();
    private DevolucionDTO Devolucion { get; set; } = new();
    private string _responsableEmail = string.Empty;

    protected override async Task OnInitializedAsync()
    {
        try
        {
            var peticion = await Http.Get<TramiteDTO>($"api/tramites/{TramiteId}");

            if (peticion.Error)
            {
                await Mensaje.Error("No fue posible obtener los datos del trámite");
            }
            else
            {
                var autenticacion = await Authentication;
                var usuario = autenticacion.User;

                _responsableEmail = usuario.FindFirst(ClaimTypes.Email).Value;
                Tramite = peticion.Respuesta;
            }
        }
        catch (Exception)
        {
            await Mensaje.Error("Ocurrio un error inesperado");
        }
    }

    private async Task Finalizar()
    {
        try
        {
            var peticion = await Http.Post<int?>($"api/tramites/finalizar", TramiteId);

            if (peticion.Error)
            {
                await Mensaje.Error("No fue posible finalizar el trámite");
            }
            else
            {
                await Registro.Generar(_responsableEmail, $"Agregó el trámite con expediente [{Tramite.Expediente}] a la lista de finalizados");
                await Mensaje.Completado("El trámite fue finalizado con éxito");
                Navigation.NavigateTo("tramites/finalizados");
            }
        }
        catch (Exception)
        {
            await Mensaje.Error("Ocurrio un error inesperado");
        }
    }

    private async Task Archivar()
    {
        try
        {
            var archivar = new ArchivarDTO();

            archivar.TramiteId = TramiteId;
            archivar.ArchivadoDesde = "Para entregar";
            archivar.Estado = "Archivado";

            if (await Mensaje.Confirmar($"Archivar trámite"))
            {
                var respuesta = await Http.Post<ArchivarDTO>("api/tramites/archivar", archivar);

                if (respuesta.Error)
                {
                    await Mensaje.Error(await respuesta.ObtenerMensaje());
                }
                else
                {
                    await Registro.Generar(_responsableEmail, $"Agregó el trámite con expediente [{Tramite.Expediente}] a la lista de archivados");
                    await Mensaje.Completado("El trámite fue archivado con éxito");
                    Navigation.NavigateTo("tramites/archivados");
                }
            }
        }
        catch (Exception)
        {
            await Mensaje.Error("Ocurrio un error inesperado");
        }
    }
}
